name: tests

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install V
      uses: vlang/setup-v@v1.4
      with:
        check-latest: true
    - name: Build
      run: v -prod src/ -o target/lule
    - name: Vet
      run: v vet src/
    - name: Smoke test
      run: |
        LULE_A=$(mktemp -d) LULE_S= target/lule create --image=resources/theme_dark.png -- set
        LULE_A=$(mktemp -d) LULE_S= target/lule --version
